### ISSUE TITLE
Disallow Text Highlight (minor)

### ISSUE THREAD

**Issue by c0nsole2600** [Trimps/Trimps.github.io#77]
I ran across Trimps a few months ago and love it.  Great work!

I haven't really come across any major defects, but I did want to mention that all of the non-clickable elements like text headers are selectable (highlightable).  For my play style, this becomes a bit annoying when clicking quickly to purchase upgrades.  As I quickly click to purchase all of the upgrades, the Equipment section moves up and I accidentally double click on the Equipment header which highlights the text.  I was hoping you could add a little css to make the headers non-selectable (I can't imagine a reason someone would need to highlight a header).

I have been been adding this css to the body in chrome developer tools to avoid the accidental highlight annoyance.  Of course, I have to add it back each time I open the page.

```css
body {
  user-select: none;
}
```

A cross-browser solution would be 

```css
body {
  -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Chrome/Safari/Opera */
     -khtml-user-select: none; /* Konqueror */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version */
}
```

This is an easy fix to add to the css, but it is a bit hacky since it still shows the "I" text select cursor when you hover over text.  A better, however more time consuming, solution would be to add a label class to all the headers/labels that do not need to be highlighted.  The label class would contain user-select: none; and cursor: default;.

```css
.label {
  -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Chrome/Safari/Opera */
     -khtml-user-select: none; /* Konqueror */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version */
  cursor: default; /* forces the cursor to be the default arrow icon */
}
```

I appreciate you listening to my feedback.  Great work on the game!  I'm really enjoying it.
